[package]
name = "rust_mark"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
dirs = "6.0.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.2"
unicode-segmentation = "1.12.0"
unicode_categories = "0.1.1"

[[bin]]
name = "rust-mark"
path = "src/main.rs"
