name: CI
on:
  push:
    branches: ["main"]
    paths-ignore: ["README.md", ".gitignore"]
  pull_request: {}

jobs:
  verify-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Build
        run: cargo build --verbose

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Tests
        run: cargo test --verbose

