name: Publish
on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Publish to crates.io
        run: cargo release --publish --no-confirm minor
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
