name: Build and Release Binary
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            ext: tar.gz
          - os: windows-latest
            ext: zip
          - os: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build binary
        run: cargo build --release

      - name: Prep artifact
        run: |
          mkdir dist
          cp target/release/${{ github.event.repository.name }}* dist/
        shell: bash

      - name: Compress artifact
        run: |
          cd dist
          if [ "${{ matrix.ext }}" = "zip" ]; then
            powershell Compress-Archive -Path * -DestinationPath ../${{ runner.os }}.zip
          else
            tar -czvf ../${{ runner.os }}.tar.gz *
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifact
          path: |
            *.zip
            *.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*.*
          token: ${{ secrets.PAT_TOKEN }}
