name: Run Cargo Tests
on:
  push:
    branches: ["main"]
    paths-ignore: ["README.md", ".gitignore", ".github/**"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests
        run: cargo test --verbose
